# Generated by Django 6.0.5 on 2026-05-23 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_register_delete_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Avtobus raqami"
                    ),
                ),
                (
                    "route",
                    models.CharField(max_length=20, verbose_name="Yo'nalish (Route)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyTripLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Sana")),
                (
                    "trips_completed",
                    models.IntegerField(default=0, verbose_name="Bajarilgan qatnovlar"),
                ),
                (
                    "trips_missed",
                    models.IntegerField(
                        default=0, verbose_name="Qolib ketgan qatnovlar"
                    ),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to="apps.bus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Foydalanuvchi ismi"),
                ),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("even", "Juft kunlar (Even)"),
                            ("odd", "Toq kunlar (Odd)"),
                        ],
                        default="even",
                        max_length=10,
                    ),
                ),
                (
                    "black",
                    models.BooleanField(
                        default=False, verbose_name="Qora ro'yxat / Maxsus holat"
                    ),
                ),
                ("shift_start", models.TimeField(verbose_name="Smena boshi")),
                ("shift_end", models.TimeField(verbose_name="Smena oxiri")),
                (
                    "total_trips",
                    models.IntegerField(default=0, verbose_name="Jami qatnovlar soni"),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drivers",
                        to="apps.bus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        max_length=100, verbose_name="Xizmat turi (TO-1, TO-2...)"
                    ),
                ),
                (
                    "planned_date",
                    models.DateField(verbose_name="Rejalashtirilgan sana"),
                ),
                (
                    "days_remaining",
                    models.IntegerField(verbose_name="Qolgan kunlar soni"),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_schedules",
                        to="apps.bus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechnicalStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tires", "Shinalar (Tires)"),
                            ("brakes", "Tormoz (Brakes)"),
                            ("oil", "Moy / Antifriz (Oil)"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "last_service_date",
                    models.DateField(verbose_name="Oxirgi texnik ko'rik sanasi"),
                ),
                (
                    "current_km",
                    models.IntegerField(verbose_name="Hozirgi yurgan masofasi (km)"),
                ),
                (
                    "max_km",
                    models.IntegerField(
                        default=50000,
                        verbose_name="Maksimal ruxsat etilgan masofa (km)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Yaxshi (OK)"),
                            ("warn", "Ogohlantirish (Warning)"),
                            ("danger", "Xavfli (Danger)"),
                        ],
                        default="ok",
                        max_length=10,
                    ),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tech_statuses",
                        to="apps.bus",
                    ),
                ),
            ],
            options={
                "unique_together": {("bus", "category")},
            },
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="Register",
        ),
        migrations.AddField(
            model_name="dailytriplog",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_logs",
                to="apps.driver",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailytriplog",
            unique_together={("date", "bus", "driver")},
        ),
    ]
