# Generated by Django 6.0.5 on 2026-05-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_bus_dailytriplog_driver_maintenanceschedule_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technicalstatus",
            name="category",
            field=models.CharField(
                choices=[
                    ("tires", "Shinalar (Tires)"),
                    ("brakes", "Tormoz (Brakes)"),
                    ("oil", "Moy / Antifriz (Oil)"),
                    ("engine", "Dvigatel (Engine)"),
                    ("battery", "Akkumulyator (Battery)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="technicalstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "Yaxshi (OK)"),
                    ("warn", "Ogohlantirish (Warning)"),
                    ("danger", "Xavfli (Danger)"),
                    ("repair", "Ta’mir talab"),
                ],
                default="ok",
                max_length=10,
            ),
        ),
    ]
