# Generated by Django 6.0.5 on 2026-06-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0005_alter_technicalstatus_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="route",
            field=models.IntegerField(max_length=20, verbose_name="Yo'nalish (Route)"),
        ),
    ]
