# Generated by Django 6.0.5 on 2026-06-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0006_alter_bus_route"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="route",
            field=models.CharField(max_length=20, verbose_name="Yo'nalish (Route)"),
        ),
    ]
