# Generated by Django 6.0.5 on 2026-06-27 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_bus_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Haydovchi ismi'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='shift_end',
            field=models.TimeField(default='18:00', verbose_name='Smena oxiri'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='shift_start',
            field=models.TimeField(default='06:00', verbose_name='Smena boshi'),
        ),
        migrations.AlterField(
            model_name='technicalstatus',
            name='status',
            field=models.CharField(choices=[('ok', 'Yaxshi (OK)'), ('warn', 'Ogohlantirish (Warning)'), ('danger', 'Xavfli (Danger)'), ('repair', "Ta'mir talab")], default='ok', max_length=10),
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Jarima sanasi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, max_length=12, verbose_name="Jarima summasi (so'm)")),
                ('reason', models.CharField(max_length=255, verbose_name='Jarima sababi')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='apps.driver', verbose_name='Haydovchi')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Yil')),
                ('month', models.IntegerField(verbose_name='Oy (0-11 yoki 1-12)')),
                ('fixed_salary', models.DecimalField(decimal_places=2, max_digits=12, max_length=12, verbose_name='Kafolatlangan oylik (Fiksa)')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12, max_length=12, verbose_name='Mukofot puli / Bonus')),
                ('fines_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, max_length=12, verbose_name='Jrimadan ushlab qolingan')),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=12, max_length=12, verbose_name="Qo'lga tegadigan jami summa")),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='apps.driver', verbose_name='Haydovchi')),
            ],
            options={
                'unique_together': {('driver', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='WorkAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('planned_hours', models.IntegerField(default=8, verbose_name='Rejalashtirilgan vaqt (soat)')),
                ('actual_hours', models.IntegerField(default=0, verbose_name='Haqiqiy ishlagan vaqti (soat)')),
                ('overtime_hours', models.IntegerField(default=0, verbose_name='Ortiqcha ishlagan vaqti (soat)')),
                ('status', models.CharField(default='Ishda', max_length=50, verbose_name='Status / Izoh')),
                ('check_in', models.TimeField(blank=True, default='06:00', null=True, verbose_name='Kelgan vaqti')),
                ('check_out', models.TimeField(blank=True, default='22:30', null=True, verbose_name='Ketgan vaqti')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='apps.driver', verbose_name='Haydovchi')),
            ],
            options={
                'unique_together': {('driver', 'date')},
            },
        ),
    ]
