# Generated by Django 6.0.5 on 2026-06-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_driver_phone_alter_driver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='shift_end',
            field=models.TimeField(blank=True, default='18:00', null=True, verbose_name='Smena oxiri'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='shift_start',
            field=models.TimeField(blank=True, default='06:00', null=True, verbose_name='Smena boshi'),
        ),
    ]
