# Generated by Django 6.0.5 on 2026-07-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_driver_shift_end_alter_driver_shift_start'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together=set(),
        ),
    ]
